- name: Install RPMFusion
  ansible.builtin.dnf:
    name:
      - https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ release_ver }}.noarch.rpm
      - https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ release_ver }}.noarch.rpm
    disable_gpg_check: true
    state: present

- name: DNF Update
  ansible.builtin.dnf:
    name: "*"
    state: latest
    update_cache: yes