---
- name: Common program installation
  hosts: all
  become: yes
  roles:
    - common
    - rpmfusion
    - dnf
#    - codecs  # Commented out because this does not need to be run if using flatpaks. Use at your own risk!
    - flatpak

