- name: Update DNF cache
  ansible.builtin.dnf:
    name: "*"
    state: latest
    update_cache: yes

- name: DNF Swap ffmpeg
  ansible.builtin.command: dnf swap -y ffmpeg-free ffmpeg --allowerasing
  become: yes
  become_method: sudo
  
- name: install additional codecs
  ansible.builtin.command: dnf update -y @multimedia --setopt="install_weak_deps=False" --exclude=PackageKit-gstreamer-plugin
  become: yes
  become_method: sudo 

- name: DNF Swap mesa-va-drivers
  ansible.builtin.command: dnf swap -y mesa-va-drivers mesa-va-drivers-freeworld
  become: yes
  become_method: sudo
  

- name: DNF Swap mesa-vdpau-drivers
  ansible.builtin.command: dnf swap -y mesa-vdpau-drivers mesa-vdpau-drivers-freeworld 
  become: yes
  become_method: sudo 
